=== shimebet/mulesoft-course-data/Free_MuleSoft_Developer_Course/dataweave-metadata-single-record/src/main/resources/schemas/bookstore_json_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "category": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "lang": {
      "type": "string"
    },
    "author": {
      "type": "string"
    },
    "year": {
      "type": "integer"
    },
    "price": {
      "type": "number"
    }
  },
  "required": [
    "category",
    "title",
    "lang",
    "author",
    "year",
    "price"
  ]
}

=== shimebet/mulesoft-course-data/Free_MuleSoft_Developer_Course/dataweave-metadata/src/main/resources/examples/bookstore.json
[
  {
    "category": "cooking",
    "title": "Everyday Italian",
    "lang": "en",
    "author": "Giada De Laurentiis",
    "year": 2005,
    "price": 30
    
  },
  {
    "category": "children",
    "title": "Harry Potter",
    "lang": "en",
    "author": "J K. Rowling",
    "year": 2005,
    "price": 29.99
  },
  {
    "category": "web",
    "title": "Learning XML",
    "lang": "en",
    "author": "Erik T. Ray",
    "year": 2003,
    "price": 39.95
  }
]
